# Generated by Django 4.2 on 2023-04-26 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_person"),
    ]

    operations = [
        migrations.RenameField(
            model_name="person",
            old_name="person_email",
            new_name="email",
        ),
        migrations.RenameField(
            model_name="person",
            old_name="person_id",
            new_name="id",
        ),
    ]
