# Generated by Django 4.2 on 2023-04-27 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_rename_person_email_person_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="role",
            field=models.CharField(max_length=15),
        ),
    ]
