# Generated by Django 4.2 on 2023-04-29 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_person_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="is_contributor",
            field=models.BooleanField(default=False),
        ),
    ]
