# Generated by Django 4.2 on 2023-04-29 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_person_is_contributor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="is_contributor",
        ),
    ]
