# Generated by Django 4.2 on 2023-04-24 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LC_SearchEngine", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Users",
        ),
        migrations.AlterField(
            model_name="leetcodedata",
            name="accepted",
            field=models.CharField(max_length=5),
        ),
    ]
