# Generated by Django 4.2 on 2023-04-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LC_SearchEngine", "0002_delete_users_alter_leetcodedata_accepted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leetcodedata",
            name="accepted",
            field=models.CharField(max_length=7),
        ),
    ]
