# Generated by Django 4.2 on 2023-04-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LC_SearchEngine", "0003_alter_leetcodedata_accepted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leetcodedata",
            name="acceptance_rate",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="leetcodedata",
            name="accepted",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="leetcodedata",
            name="frequency",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="leetcodedata",
            name="related_topics",
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name="leetcodedata",
            name="solution_link",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="leetcodedata",
            name="submissions",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="leetcodedata",
            name="url",
            field=models.CharField(max_length=200),
        ),
    ]
