# Generated by Django 4.2 on 2023-04-24 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LC_SearchEngine", "0004_alter_leetcodedata_acceptance_rate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leetcodedata",
            name="similar_questions",
            field=models.TextField(blank=True, null=True),
        ),
    ]
